dataset: "hlagcn"
padding: False
augmentation: 1

# Training
epochs: 10
batch_size: 16
accum_steps: 4
num_workers: 8

lr: 0.0001
lambda_mean: 0.2
lambda_rank: 0.1

# Model
query_size: 768
num_visual_query: 2
num_text_query: 2
num_attn_heads: 8
max_caption_length: 512
dropout: 0.1

# Encoder
vision_freeze: False
swin_pretrained: ""
parn_pretrained: ""

# Resume
resume: ""
